# Generated by Django 4.1 on 2023-07-04 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('variation_type', models.CharField(max_length=100)),
                ('variation_name', models.CharField(max_length=250)),
                ('short_description', models.TextField(blank=True, default='0', max_length=1200)),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.ImageField(upload_to='product-images')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('schedule_discount', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=250)),
                ('short_description', models.TextField(blank=True, default='0', max_length=1200)),
                ('description', models.TextField(max_length=5000)),
                ('thumbnail', models.ImageField(upload_to='product-images')),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('schedule_discount', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariationsImageGallery',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product-image-gallery')),
                ('variant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_product_image_gallery', to='adminpanel.productvariation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='adminpanel.shopproduct'),
        ),
        migrations.CreateModel(
            name='ProductImageGallery',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product-image-gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image_gallery', to='adminpanel.shopproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
