# Generated by Django 4.2.3 on 2023-07-15 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation_type', models.CharField(max_length=100)),
                ('variation_name', models.CharField(max_length=250)),
                ('short_description', models.TextField(blank=True, default='0', max_length=1200)),
                ('sku', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product-images')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=60)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('schedule_discount', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField(default=10)),
                ('out_of_stock', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=250)),
                ('short_description', models.TextField(blank=True, default='0', max_length=1200)),
                ('description', models.TextField(max_length=5000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product-images')),
                ('sku', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=60)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('schedule_discount', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField(default=10)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('have_variant', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariationsImageGallery',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-image-gallery')),
                ('variant_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_product_images', to='adminpanel.productvariation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_products', to='adminpanel.shopproduct'),
        ),
        migrations.CreateModel(
            name='ProductImageGallery',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-image-gallery')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='adminpanel.shopproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.FileField(blank=True, upload_to='media-files/2023/07')),
                ('author', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='adminpanel.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='adminpanel.shopproduct')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='adminpanel.productvariation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
