# Generated by Django 4.2.3 on 2023-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_shopproduct_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.CharField(blank=True, default=['8e62d5fe', 'c06d', '4f9e', 'abb3', '26add8efe4fd'], max_length=200, unique=True),
        ),
    ]
