# Generated by Django 4.1 on 2023-07-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_productimagegallery_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
