# Generated by Django 4.2.3 on 2023-07-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_shopproduct_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
