# Generated by Django 4.2.3 on 2023-07-04 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_productvariation_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, max_length=350),
        ),
    ]
