# Generated by Django 4.2.3 on 2023-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_shopproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='have_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
