# Generated by Django 4.2.3 on 2023-07-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_productvariation_out_of_stock_productvariation_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagegallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='adminpanel.shopproduct'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_products', to='adminpanel.shopproduct'),
        ),
        migrations.AlterField(
            model_name='productvariationsimagegallery',
            name='variant_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_product_images', to='adminpanel.productvariation'),
        ),
    ]
