# Generated by Django 4.2.3 on 2023-07-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_productimagegallery_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, unique=True),
        ),
    ]
