# Generated by Django 4.2.3 on 2023-07-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_shopproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-image-gallery'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product-images'),
        ),
        migrations.AlterField(
            model_name='productvariationsimagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-image-gallery'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product-images'),
        ),
    ]
