# Generated by Django 4.2.3 on 2023-07-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_productimagegallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_products', to='adminpanel.shopproduct'),
        ),
    ]
