# Generated by Django 4.2.3 on 2023-07-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_imagegallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'ordering': ('-created_at',)},
        ),
    ]
