# Generated by Django 4.2.3 on 2023-07-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='blog.category'),
        ),
    ]
