# Generated by Django 4.2.3 on 2023-07-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_replied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='19e72906-51a2-4998-a0a1-aca503284bbd', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='blog.category'),
        ),
    ]
